name: Greeting on variable day

on:
  push

env:
  DAY_OF_WEEK: Monday
  DB_NAME: ${{ secrets.MONGODB_USERNAME }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: |
          echo "${{ env.Greeting }} ${{ env.First_Name }}. Today is ${{ env.DAY_OF_WEEK }}!"
          echo "DB_NAME is ${{env.DB_NAME}}"
          echo "DB_NAME is $DB_NAME"
        env:
          First_Name: Mona
