name: Deployment
on:
  push:
    branches:
      - main
      - dev
env:
    MONGODB_DB_NAME: hello-db
jobs:
  test:
    env:
      PORT: 8080
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "MONGODB_DB_NAME: ${{env.MONGODB_DB_NAME}}"
          echo "PORT: ${{env.PORT}}"